### ISSUE TITLE
Windows gbk encoded zip archive decompression exception

### ISSUE THREAD

**Issue by wkl007** [use-strict/7z-wasm#15] opened 2023-03-16 04:38 UTC
[异常压缩包.zip](https://github.com/use-strict/7z-wasm/files/10986629/default.zip)

```
7z-wasm e 异常压缩包.zip
```
The decompressed file name is displayed abnormally.
<img width="727" alt="image" src="https://user-images.githubusercontent.com/23228335/225515523-5d5287e9-1052-4e9f-b87d-367dbdf21645.png">

```
 7z e .\异常压缩包.zip
```
The decompressed file name is displayed normally.
<img width="731" alt="image" src="https://user-images.githubusercontent.com/23228335/225515775-0cb433a6-9e48-4ab2-ae39-c0e4715e80f9.png">

Please help me, thank you very much!!!

**Comment by use-strict** [comment] 2023-03-16 07:54
Duplicate of #8

**Closed as not planned by use-strict** 2023-03-16 07:54 UTC
